name: Cypress CI/CD Pipeline with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_IMAGE_NAME: cypress-ajax-test
  DOCKER_TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/included:14.2.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Cypress tests
        run: |
          npx cypress run --browser chrome --headless
        env:
          ELECTRON_EXTRA_LAUNCH_ARGS: --no-sandbox
          CYPRESS_FORCE_REINSTALL: 1

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}