name: Cypress CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install -g cypress
          npx cypress verify

      - name: Run Cypress tests
        run: |
          export CYPRESS_RUN_BINARY=$(which cypress)
          npx cypress run --headless --browser chrome