name: Cypress CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:14.2.1  # Key fix - uses official Docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Cypress tests
        run: |
          npx cypress run --browser chrome --headless
        env:
          # Disables Chrome sandbox which causes issues in CI
          ELECTRON_EXTRA_LAUNCH_ARGS: --no-sandbox
          # Forces fresh Chrome install
          CYPRESS_FORCE_REINSTALL: 1